geo: "zip code tabulation area"
api_key: "YOUR KEY GOES HERE" # sign up for one here: https://api.census.gov/data/key_signup.html

census_tables:
  Occupation:
    source_table: B24011
    columns:
      - 001E
      - 002E
      - 003E
      - 004E
      - 005E
      - 006E
      - 007E
      - 008E
      - 009E
      - 010E
      - 011E
      - 012E
      - 013E
      - 014E
      - 015E
      - 016E
      - 017E
      - 018E
      - 019E
      - 020E
      - 021E
      - 022E
      - 023E
      - 024E
      - 025E
      - 026E
      - 027E
      - 028E
      - 029E
      - 030E
      - 031E
      - 032E
      - 033E
      - 034E
      - 035E
      - 036E
    column_names:
      - Total
      - ManagementBusinessScienceArts
      - ManagementBusinessScienceArts_Financials
      - ManagementBusinessScienceArts_Management
      - ManagementBusinessScienceArts_Business
      - ManagementBusinessScienceArts_ComputerEngineering
      - ManagementBusinessScienceArts_Computers
      - ManagementBusinessScienceArts_Architecture
      - ManagementBusinessScienceArts_LifePhyiscalScience
      - ManagementBusinessScienceArts_EducationLegalCommunityMedia
      - ManagementBusinessScienceArts_EducationLegalCommunityMedia_CommunitySocialService
      - ManagementBusinessScienceArts_EducationLegalCommunityMedia_Legal
      - ManagementBusinessScienceArts_EducationLegalCommunityMedia_EducationLibrary
      - ManagementBusinessScienceArts_EducationLegalCommunityMedia_ArtsMediaEntertainment
      - ManagementBusinessScienceArts_Healthcare
      - ManagementBusinessScienceArts_Healthcare_DiagnoseTreatment
      - ManagementBusinessScienceArts_Healthcare_HeathTechnicians
      - Service
      - Service_HeathcareSupport
      - Service_Protective
      - Service_Firefighting
      - Service_LawEnforcement
      - TOtalService_FoodPreparation
      - Service_BuildingMaintenance
      - Service_PersonalCare
      - SalesOffice
      - SalesOffice_Sales
      - SalesOffice_OfficeAdmin
      - NaturalResourcesConstructionMaintenance
      - NaturalResourcesConstructionMaintenance_FarmingFishingForestry
      - NaturalResourcesConstructionMaintenance_ConstructionMining
      - NaturalResourcesConstructionMaintenance_InstallationRepair
      - ProductionTransportion
      - ProductionTransportion_Production
      - ProductionTransportion_Transportation
      - ProductionTransportion_Moving
  HouseValue:
    source_table: B25075
    columns:
      - 001E
      - 002E
      - 003E
      - 004E
      - 005E
      - 006E
      - 007E
      - 008E
      - 009E
      - 010E
      - 011E
      - 012E
      - 013E
      - 014E
      - 015E
      - 016E
      - 017E
      - 018E
      - 019E
      - 020E
      - 021E
      - 022E
      - 023E
      - 024E
      - 025E
      - 026E
      - 027E
    column_names:
      - Total
      - HouseValue_10000
      - HouseValue_10000to14999
      - HouseValue_15000to19999
      - HouseValue_20000to24999
      - HouseValue_25000to29999
      - HouseValue_30000to34999
      - HouseValue_35000to39999
      - HouseValue_40000to49999
      - HouseValue_50000to59999
      - HouseValue_60000to69999
      - HouseValue_70000to79999
      - HouseValue_80000to89999
      - HouseValue_90000to99999
      - HouseValue_100000to124999
      - HouseValue_125000to149999
      - HouseValue_150000to174999
      - HouseValue_175000to199999
      - HouseValue_200000to249999
      - HouseValue_250000to299999
      - HouseValue_300000to399999
      - HouseValue_400000to499999
      - HouseValue_500000to749999
      - HouseValue_750000to999999
      - HouseValue_1000000to1499999
      - HouseValue_1500000to1999999
      - HouseValue_2000000AndAbove
  HouseholdIncome:
    source_table: B19001
    columns:
      - 001E
      - 002E
      - 003E
      - 004E
      - 005E
      - 006E
      - 007E
      - 008E
      - 009E
      - 010E
      - 011E
      - 012E
      - 013E
      - 014E
      - 015E
      - 016E
      - 017E
    column_names:
      - TotalHousehold
      - TotalHHLessThan10000
      - TotalHH10000to14999
      - TotalHH15000to19999
      - TotalHH20000to24999
      - TotalHH25000to29999
      - TotalHH30000to34999
      - TotalHH35000to39999
      - TotalHH40000to44999
      - TotalHH45000to49999
      - TotalHH50000to59999
      - TotalHH60000to74999
      - TotalHH75000to99999
      - TotalHH100000to124999
      - TotalHH125000to149999
      - TotalHH150000to199999
      - TotalHHOver200000
